apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: weather-instrumentation
spec:
  python:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: "true"
      - name: OTEL_SERVICE_NAME
        value: weather.api
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.name=weather.api,deployment.environment=prod,application.name=weather.api"
