apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: weather-instrumentation
  namespace: weather
spec:
  exporter:
    endpoint: http://172.23.0.2:4318
  propagators:
    - tracecontext
    - baggage
  python:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: "true"
      - name: OTEL_SERVICE_NAME
        value: weather-api
