apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
  namespace: weather
type: Opaque
stringData:
  DB_HOST: host.docker.internal
  DB_PORT: "5432"
  DB_NAME: weather-db
  DB_USER: postgres
  DB_PASSWORD: postgres
  OTEL_ENDPOINT: http://172.23.0.2:4318
