apiVersion: apps/v1
kind: Deployment
metadata:
  name: shape-notification-api
  namespace: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shape-notification-api
  template:
    metadata:
      labels:
        app: shape-notification-api
        app_name: shape.notification-api
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
        - name: shape-notification-api
          image: shape-notification-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: EVENT_HUB_CONNECTION_NOTIFICATION_SEND
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: EVENT_HUB_CONNECTION_NOTIFICATION_SEND
            - name: EVENT_HUB_NOTIFICATION
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: EVENT_HUB_NOTIFICATION
            - name: EVENT_HUB_CONSUMER_GROUP
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: EVENT_HUB_CONSUMER_GROUP
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: APP_ENV
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: HOST
            - name: OTEL_ENABLED
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: OTEL_ENABLED
            - name: OTEL_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: OTEL_SERVICE_NAME
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              valueFrom:
                secretKeyRef:
                  name: notification-api-secret
                  key: OTEL_SEMCONV_STABILITY_OPT_IN
