apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: notification-api-instrumentation
  namespace: notification-api
spec:
  exporter:
    endpoint: http://172.23.0.50:4318
  propagators:
    - tracecontext
    - baggage
  python:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: "true"
      - name: OTEL_SERVICE_NAME
        value: shape.notification.api
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.name=shape.notification.api,application.name=shape.notification.api"
