apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-dev

resources:
  - ../../base
  - secret.yaml

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: weather-api
  - path: patch-instrumentation.yaml
    target:
      kind: Instrumentation
      name: weather-instrumentation
